### ISSUE TITLE
Events homepage view: Janis

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3818]
### As a resident, I want to learn about events the City offers that are relevant to me, so that I can find one to attend.

**Design matches mocks**

- [ ] [Overview](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/)
- [ ] Home page: [desktop](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/8d5f7c07-f178-473d-91cb-77a50ad353a0/Event-MVP-Home-Desktop)
- [ ] Home page: [mobile](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/3d291391-3fdf-4bdd-876a-d0f51aa9fcb0/Event-MVP-Home-Mobile)

**Number of events listed**
- [x] Max: 3
- [x] If 0: do not display the component

**Fee and registration display**
- [x] If there’s a registration link on Joplin display “Registration required”, this won’t be a link

**Possible combinations**
- [x] Free
- [x] Free • Registration required 
- [ ] Registration required 
- [x] $1 
- [x] $1–$5
- [x] $1 • Registration required
- [x] $1–$5 • Registration required

**Location display**
- [x] Display name of location, exclude address
- [ ] ~~If no location name, display address~~ name of venue is currently required for remote locations, and City locations will always have a location page
- [x] Don’t display “Get directions”

**Display**
- [ ] Mobile: vertical list
- [ ] Desktop: minimum width: 277px, below which the component should switch to the list vertical view

**Comment by desigonz** [comment]
@briaguya updated some of the acceptance criteria above, based on @chasechenevert's comments in #3724

**Comment by chiaberry** [comment]
https://janis-3818-event-home.netlify.com/

@desigonz @chasechenevert ready for QA -- if an event is cancelled, does it still show up on the homepage?

**Comment by chasechenevert** [comment]
> https://janis-3818-event-home.netlify.com/
> 
> @desigonz @chasechenevert ready for QA -- if an event is cancelled, does it still show up on the homepage?

Based on some stuff we decided awhile back we're going to hide events that are cancelled on the homepage.

**Comment by chiaberry** [comment]
thank you, ill update the code to remove canceled events

**Comment by desigonz** [comment]
@chiaberry Can you add a Joplin link for testing? I want to add events and see how that affects homepage display.

**Comment by chiaberry** [comment]
here is the joplin link: https://joplin-pr-3818-event-home.herokuapp.com/admin/pages/search/

**Comment by chiaberry** [comment]
I merged the joplin branch, forgetting that means the heroku app is deleted. so heres a new one: https://joplin-pr-3818-event-home2.herokuapp.com/

its building right now but will be ready in a few minutes

**Comment by desigonz** [comment]
Hi @chiaberry! Awesome work. I'm going to go down the acceptance criteria list using various combos of test data, but @chasechenevert, please review the designs at mobile/tablet/desktop sizes. I'm noticing some funny things happening on tablet and mobile sizes
![image](https://user-images.githubusercontent.com/5839508/75292072-1cc6ab80-57e9-11ea-9ae5-e92fd838bcc2.png)
![image](https://user-images.githubusercontent.com/5839508/75292206-61524700-57e9-11ea-882d-36450ba478bd.png)
![image](https://user-images.githubusercontent.com/5839508/75292239-6d3e0900-57e9-11ea-9d13-4fdb7aba77a9.png)

**Comment by desigonz** [comment]
Okay all of the different data combos look good. I think it's a matter of mobile and tablet views, which @chasechenevert can comment on. I'm going to unassign myself from this for now!

**Comment by desigonz** [comment]
One last thing for @chiaberry and this might need more testing: I [unpublished all of the events on the Joplin side](https://joplin-pr-3818-event-home2.herokuapp.com/admin/pages/search/?q=&content_type=events.eventpage), but they still all appear on the [homepage](https://janis-3818-event-home.netlify.com/). Thoughts on what might be going on?

**Comment by chiaberry** [comment]
@desigonz okay! now that heroku is cooperating, I've pushed up a fix that makes it so *no* unpublished page slips into the site structure. this should fix not only events, but also locations and all other content types.

**Comment by desigonz** [comment]
Neat!! Can I test at the same Joplin/Janis links?

**Comment by chiaberry** [comment]
yes!

**Comment by desigonz** [comment]
Awesome work!! I tested it and it looks good. 

I also tested unpublishing the "Get bulk items collection" page. The page is now unpublished (it [404s](https://janis-3818-event-home.netlify.com/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/)), but it's still appearing on the topic page. I'm going to spin this out into its own issue, so no need to worry about this.

Next steps:
- @chiaberry, did you see the screenshots I included above for mobile and tablet view? I think that's all that needs to get fixed
- @chasechenevert to review the design implementation

**Comment by chasechenevert** [comment]
@chiaberry the example that I'm reviewing https://janis-3818-event-home.netlify.com/ only has one event, is there an example with 3? Just want to make sure I'm checking right right link

**Comment by desigonz** [comment]
That's because I was testing what 1 looks like! You can add them at the Joplin link: https://joplin-pr-3818-event-home2.herokuapp.com/

**Comment by chiaberry** [comment]
@chasechenevert & @desigonz updated for tablet views

same janis, https://janis-3818-event-home.netlify.com/, but its linked to joplin-staging now

**Comment by desigonz** [comment]
Awesome, thanks @chiaberry! 

I'm still getting overlap at very narrow widths:
![image](https://user-images.githubusercontent.com/5839508/75685509-473cbc80-5c60-11ea-8eae-36131b498724.png)

But looks better when viewed on a mobile device:
![image](https://user-images.githubusercontent.com/5839508/75685553-5b80b980-5c60-11ea-950e-7902d28f742c.png)

**Comment by chiaberry** [comment]
@desigonz I fixed the white overlap

**Comment by desigonz** [comment]
@chiaberry beautiful! QA is done on my side of things but I'll let @chasechenevert have the final word.

**Comment by chasechenevert** [comment]
This is good to go!
